# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

_file_map = {

    "clients.baml": "client<llm> PolicyClient {\n  provider google-ai\n  options {\n    model \"gemini-2.5-flash\"\n    api_key env.GOOGLE_API_KEY\n    temperature 0\n  }\n}\n",
    "generators.baml": "generator target {\n    output_type \"python/pydantic\"\n    output_dir \"../app/baml_client\"\n    version \"0.222.0\"\n    default_client_mode \"async\"\n}\n",
    "moderation.baml": "enum ScopeDecision {\n  IN_SCOPE\n  OUT_OF_SCOPE\n  AMBIGUOUS\n}\n\nclass ScopeCheckResult {\n  decision ScopeDecision\n  reason_code string\n  explanation string\n}\n\nfunction ScopeCheck(\n  company_name: string,\n  supported_topics: string[],\n  forbidden_topics: string[],\n  message: string\n) -> ScopeCheckResult {\n  client PolicyClient\n  prompt #\"\n    You classify whether a user's message is inside or outside the customer support scope for {{ company_name }}.\n\n    Supported topics:\n    {% for topic in supported_topics %}\n    - {{ topic }}\n    {% endfor %}\n\n    Explicitly out-of-scope topics:\n    {% for topic in forbidden_topics %}\n    - {{ topic }}\n    {% endfor %}\n\n    Classification rules:\n    - Return IN_SCOPE only when the user is clearly asking for company support.\n    - Return OUT_OF_SCOPE for trivia, unrelated general knowledge, unrelated chit-chat, competitor research, or other non-support requests.\n    - Return AMBIGUOUS only when the message could plausibly be support-related but lacks enough context.\n    - If the message is clearly unrelated, prefer OUT_OF_SCOPE instead of AMBIGUOUS.\n    - reason_code must be short snake_case text.\n    - explanation must be one concise sentence.\n\n    User message:\n    {{ message }}\n\n    {{ ctx.output_format }}\n  \"#\n}\n",
}

def get_baml_files():
    return _file_map